# Generated by Django 3.0.3 on 2020-07-20 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineModel',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='Student_has_Discipline',
            fields=[
                ('student_has_discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscool.DisciplineModel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscool.StudentModel')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliationModel',
            fields=[
                ('avaliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre'), ('3', '3º Semestre')], max_length=10)),
                ('note', models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)])),
                ('student_has_discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscool.Student_has_Discipline')),
            ],
        ),
    ]
