# Generated by Django 3.0.3 on 2020-07-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineModel',
            fields=[
                ('discipline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('discipline', models.ManyToManyField(blank=True, to='iscool.DisciplineModel')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliationModel',
            fields=[
                ('avaliation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre'), ('3', '3º Semestre')], max_length=10)),
                ('note', models.FloatField()),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscool.DisciplineModel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscool.StudentModel')),
            ],
        ),
    ]
