# Generated by Django 3.0.3 on 2020-09-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
    ]
