# Generated by Django 3.1.1 on 2020-09-22 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscool', '0003_auto_20200913_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Idade'),
        ),
    ]
